trigger:
- main

resources:
- repo: self

variables:
  vmImageName: 'ubuntu-latest'
  Path_YAMLIntegrationTests: './src'
  UrlReleasePopeye: 'https://github.com/derailed/popeye/releases/download/v0.22.1/popeye_linux_amd64.tar.gz'

stages:
- stage: SecurityAnalysis
  displayName: Security Analysis stage
  jobs:
  - job: SecurityAnalysis
    displayName: Security Analysis
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        kind
        cd $(Path_YAMLIntegrationTests)
        kind create cluster --name kind-01 --config=kind-cluster-config-automation-env.yaml
      displayName: Criar cluster Kubernetes local com kind
    - script: |
        echo ' '
        echo 'Cluster Kubernetes local em funcionamento...'
        echo ' '
        kubectl get services
      displayName: Verificar cluster Kubernetes local criado com kind
    - script: docker container ls
      displayName: Exibir containers em execução
    - script: |
        kubectl create namespace integrationtests
      displayName: Criar namespace integrationtests
    - script: |
        kubectl get namespaces
      displayName: Exibir namespaces criados
    - script: |
        cd $(Path_YAMLIntegrationTests)
        kubectl apply -f deployment-automation-env.yml -n integrationtests
      displayName: Criar deployment no ambiente de testes
    - script: |
        kubectl get all -n integrationtests
        echo ' '
        echo 'Aguardando a inicialização dos serviços no cluster...'
        echo ' '
        sleep 45s
        kubectl get all -n integrationtests
      displayName: Verificar subida do deployment do ambiente de testes no namespace integrationtests
    - script: |
        echo ''
        echo '***** Primeira requisicao *****'
        echo ''
        curl -s http://localhost:5000/api/contador -H "Accept: application/json" | jq
      displayName: Testes do deployment no cluster (API REST) - 1a requisicao
    - script: |
        echo ''
        echo '***** Segunda requisicao *****'
        echo ''
        curl -s http://localhost:5000/api/contador -H "Accept: application/json" | jq
      displayName: Testes do deployment no cluster (API REST) - 2a requisicao
    - script: |
        kubectl config get-contexts
      displayName: Exibir contexts/clusters disponiveis para acesso
    - script: |
        curl -L $(UrlReleasePopeye) -o popeye.tar.gz
        tar -xzf popeye.tar.gz
        sudo mv popeye /usr/local/bin/
        sudo chmod +x /usr/local/bin/popeye
      displayName: Instalar o utilitario Popeye (download + sudo)   
    - script: |
        popeye version
        echo
        popeye help
      displayName: Testar o utilitario Popeye   
    - script: |
        popeye -A
      displayName: Executar analise no cluster com o utilitario Popeye
    - script: |
        POPEYE_REPORT_DIR=$(pwd) popeye -A --save --out html --output-file report-cluster.html
      displayName: Executar analise no cluster com o utilitario Popeye gerando Report HTML
      condition: always()
    - script: |
        POPEYE_REPORT_DIR=$(pwd) popeye -A --save --out junit --output-file report-cluster.xml
      displayName: Executar analise no cluster com o utilitario Popeye gerando Report do JUNIT (.xml)
      condition: always()
    - script: |
        ls -l
      displayName: Exibir arquivos na raiz (incluindo relatorios .html e .xml)
      condition: always()
    - task: PublishHtmlReport@1
      inputs:
        reportDir: './report-cluster.html'
      displayName: Publicar resultado da analise no formato HTML
      condition: always()
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/report-cluster.xml'
      displayName: Publicar resultado no formato do JUNIT (report-cluster.xml)
      condition: always()
      
